spring:
  application:
    name: spring-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      repositories:
        enabled: false


cloud:
  aws:
    s3:
      bucket: fixspeech
    stack.auto: false
    region.static: us-east-1
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
youtube:
  api:
    key: ${YOUTUBE_KEY}